name: Docker Test Run
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '36 22 * * 2'
    
jobs:
  steps:
      runs:
        using: 'docker'
        image: 'Dockerfile'
