name: Tmux Docker test run
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '36 22 * * 2'
    
jobs:
    compile:
        name: Compile tmux
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repository
            uses: actions/checkout@v3.3.0
          - name: Run the build process with Docker
            run: docker build . --file Dockerfile --tag tmux-config-testing:$(date +%s)
